### ISSUE TITLE
dataset torrent

### ISSUE THREAD

**Issue by doctorcolossus** [chaytonmin/Off-Road-Freespace-Detection#17]
Hello!

I wanted to let you know that I have put together [a torrent of the ORFD dataset](https://academictorrents.com/details/ec5ccf4b8e49271ee3b63660383facf43063f2f2) which I've included in [a collection of datasets relevant to traversability analysis](https://academictorrents.com/collection/traversability-analysis-datasets). I hope that this can be an easier (and hopefully faster, once well seeded) alternative to Pan Baidu and Google Drive, which can involve a lot of manual clicking and interrupted downloads.

If you like this idea, please consider adding the link to your repository README and/or helping to seed. The more people who share it, the faster and easier downloading will be for others in the future. Please let me know in case you notice any issues or anything missing. Thank you!

**Comment by chaytonmin** [comment]
> Hello!
> 
> I wanted to let you know that I have put together [a torrent of the ORFD dataset](https://academictorrents.com/details/ec5ccf4b8e49271ee3b63660383facf43063f2f2) which I've included in [a collection of datasets relevant to traversability analysis](https://academictorrents.com/collection/traversability-analysis-datasets). I hope that this can be an easier (and hopefully faster, once well seeded) alternative to Pan Baidu and Google Drive, which can involve a lot of manual clicking and interrupted downloads.
> 
> If you like this idea, please consider adding the link to your repository README and/or helping to seed. The more people who share it, the faster and easier downloading will be for others in the future. Please let me know in case you notice any issues or anything missing. Thank you!

Thanks! I have added the link.
