### ISSUE TITLE
Dataset download problem!!!

### ISSUE THREAD

**Issue by mhibdredu** [chaytonmin/Off-Road-Freespace-Detection#6]
Hello,
I created baidu account and started downloading the dataset, but the prblem is the download speed is so slow , i treid to buy the premium version of baidu but i can not pay for it becuse i am in turkey and there is no payment method available for me. and i can not pay through paybal.
So can any one who hase downloaded the dataset or the author, provide another paltform for downloading, like google drive or dropbox
i will be very thankful for you.
I need this dataset i would like to tray another soultion for off-road path detection for my final year project.

**Comment by chaytonmin** [comment]
> Hello, I created baidu account and started downloading the dataset, but the prblem is the download speed is so slow , i treid to buy the premium version of baidu but i can not pay for it becuse i am in turkey and there is no payment method available for me. and i can not pay through paybal. So can any one who hase downloaded the dataset or the author, provide another paltform for downloading, like google drive or dropbox i will be very thankful for you. I need this dataset i would like to tray another soultion for off-road path detection for my final year project.

Sorry for the downloading problem.  As the capacity limit of google drive, we can not upload the full ORFD dataset.  Maybe you can downloading the small set by baidu disk and reset training and test sets.

**Comment by mhibdredu** [comment]
> another

thank you , understood. I just started downloading the dataset, after the downloading I will upload it to Google drive to use it with colab. can I ask your permission to re-share it, so another people can download it.

**Comment by mhibdredu** [comment]
> > Hello, I created baidu account and started downloading the dataset, but the prblem is the download speed is so slow , i treid to buy the premium version of baidu but i can not pay for it becuse i am in turkey and there is no payment method available for me. and i can not pay through paybal. So can any one who hase downloaded the dataset or the author, provide another paltform for downloading, like google drive or dropbox i will be very thankful for you. I need this dataset i would like to tray another soultion for off-road path detection for my final year project.
> 
> Sorry for the downloading problem. As the capacity limit of google drive, we can not upload the full ORFD dataset. Maybe you can downloading the small set by baidu disk and reset training and test sets.

thank you , understood. I just started downloading the dataset, after the downloading I will upload it to Google drive to use it with colab. can I ask your permission to re-share it, so another people can download it.

**Comment by chaytonmin** [comment]
> > > Hello, I created baidu account and started downloading the dataset, but the prblem is the download speed is so slow , i treid to buy the premium version of baidu but i can not pay for it becuse i am in turkey and there is no payment method available for me. and i can not pay through paybal. So can any one who hase downloaded the dataset or the author, provide another paltform for downloading, like google drive or dropbox i will be very thankful for you. I need this dataset i would like to tray another soultion for off-road path detection for my final year project.
> > 
> > 
> > Sorry for the downloading problem. As the capacity limit of google drive, we can not upload the full ORFD dataset. Maybe you can downloading the small set by baidu disk and reset training and test sets.
> 
> thank you , understood. I just started downloading the dataset, after the downloading I will upload it to Google drive to use it with colab. can I ask your permission to re-share it, so another people can download it.

Sure.

**Comment by Schlommy** [comment]
> > > Hello, I created baidu account and started downloading the dataset, but the prblem is the download speed is so slow , i treid to buy the premium version of baidu but i can not pay for it becuse i am in turkey and there is no payment method available for me. and i can not pay through paybal. So can any one who hase downloaded the dataset or the author, provide another paltform for downloading, like google drive or dropbox i will be very thankful for you. I need this dataset i would like to tray another soultion for off-road path detection for my final year project.
> > 
> > 
> > Sorry for the downloading problem. As the capacity limit of google drive, we can not upload the full ORFD dataset. Maybe you can downloading the small set by baidu disk and reset training and test sets.
> 
> thank you , understood. I just started downloading the dataset, after the downloading I will upload it to Google drive to use it with colab. can I ask your permission to re-share it, so another people can download it.

Hello! I too am facing issues with Baidu. Have you been able to download and reupload the data? Thanks!

**Comment by mhibdredu** [comment]
> > > > Hello, I created baidu account and started downloading the dataset, but the prblem is the download speed is so slow , i treid to buy the premium version of baidu but i can not pay for it becuse i am in turkey and there is no payment method available for me. and i can not pay through paybal. So can any one who hase downloaded the dataset or the author, provide another paltform for downloading, like google drive or dropbox i will be very thankful for you. I need this dataset i would like to tray another soultion for off-road path detection for my final year project.
> > > 
> > > 
> > > Sorry for the downloading problem. As the capacity limit of google drive, we can not upload the full ORFD dataset. Maybe you can downloading the small set by baidu disk and reset training and test sets.
> > 
> > 
> > thank you , understood. I just started downloading the dataset, after the downloading I will upload it to Google drive to use it with colab. can I ask your permission to re-share it, so another people can download it.
> 
> Hello! I too am facing issues with Baidu. Have you been able to download and reupload the data? Thanks!

HI,
Here is the linke of google drive folder where i uploaded it [Google Drive](https://drive.google.com/drive/folders/1saeASEuEpqpiM7g8Tb4Rau_vXH9tSkcZ?usp=share_link)
Here in Mega, i splieted it into 6 parts so i can upload it: 
[ORFD_Dataset_ICRA2022.z01](https://mega.nz/file/6gZnWYqR#QJLgtOJUB2pYHeI0pfLlu-C54oDmAmNa9jUiOEViGbo)
[ORFD_Dataset_ICRA2022.z02](https://mega.nz/file/uwg1DJzB#wa2SGn3-zq7c03ndIRDeD9WMY41vRovu3UlnXYJ6iHE)
[ORFD_Dataset_ICRA2022.z03](https://mega.nz/file/exxxBTQB#mt43M8zya1UBdMyGvR_MOznywMcxMFZbUEoPFTgDqEE)
[ORFD_Dataset_ICRA2022.z04](https://mega.nz/file/f9BGlAAD#8EcoG1x94JKBUUeGYJMwQ46ZGJO1Tw2NZWq4bt-OfxA)
[ORFD_Dataset_ICRA2022.z05](https://mega.nz/file/ylpyQRZD#sm6QfQaWscTzQURtiFNRHtjW6l3S348iSwEgUvf9eX8)
[ORFD_Dataset_ICRA2022.zip](https://mega.nz/file/2ppDFYzL#t89-U6zfWtod3eY0MLV3Fgoh8W6_jauEna-ItN2DjzA)

i extracted it on my local machine then reorganized and rezip before upload. Here is extraction history where i was unable to open x2021_0223_1756.zip and in other files some pictures was corrupted, so i couldnt extract it(The only corrupted pictures).i will try to unzip x2021_0223_1756.zip and reupload it, to mega and google drive.

**### Testing**
--
_x2021_0223_1756_ | P | Can not open |   |  
_y0602_1330_ (Problem with) 1623175228351.png | 1623175229852.png | 1623175230004.png
_y0609_1923_ | ok |   |   |  
_y0613_1220_ | ok |   |   |  
_y0613_1242_ | ok |   |   |  
_y2021_0228_1802_ | ok |   |   |  

**### Training**
_c2021_0228_1819_ | ok |   |   |  
_x0613_1627_ | ok |   |   |  
_x2021_0222_1720_ | ok |   |   |  
_x2021_0222_1810_ | ok |   |   |  
_x2021_0223_1310_ | ok |   |   |  
_x2021_0223_1316_ | p | 1619783766426.png |   |  
_y0602_1228_ | ok |   |   |  
_y0602_1235_ | ok |   |   |  
_y0609_1639_ | ok |   |   |  
_y0609_1750_ | p | 1623433525277.png -dense_deptg |   |  
_y0609_1954_ | ok |   |   |  
_y0609_1959_2_ | ok |   |   |  
_y0613_1238_ | ok |   |   |  
_y0613_1248_ | p | 1623722185758.bin | 1623722185840.bin |  
_y0613_1252_ | p | 1623724451845.png |   |  
_y0613_1304_ | ok |   |   |  
_y0613_1509_ | ok |   |   |  
_y0613_1632_ | ok |   |   |  
_y0616_1750_ | ok |   |   |  
_y0616_1950_ | ok |   |   |  
_y2021_0228_1807_ | ok |   |   |  

 _**### Validation**_
_x2021_0222_1745_ | ok |   |   |  
_x2021_0223_1856_ | ok |   |   |  
_y0609_1947_ | ok |   |   |  
  |   |   |   |  

</body></html></div>`

**Comment by alimertingo** [comment]
Hey man, I cannot download files from google drive, first it zipping the file then download starts. But always stick at zipping.

**Comment by chaytonmin** [comment]
> Hey man, I cannot download files from google drive, first it zipping the file then download starts. But always stick at zipping.

https://academictorrents.com/collection/traversability-analysis-datasets
